# Generated by Django 5.0.2 on 2024-02-16 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0006_delete_productalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productview',
            options={'verbose_name': 'Product View', 'verbose_name_plural': 'Product Views'},
        ),
        migrations.AlterModelOptions(
            name='socialshare',
            options={'verbose_name': 'Social Share', 'verbose_name_plural': 'Social Shares'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterField(
            model_name='productview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='productview',
            name='ip_address',
            field=models.CharField(max_length=20, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productview',
            name='session',
            field=models.CharField(max_length=100, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='socialshare',
            name='platform',
            field=models.CharField(max_length=255, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='socialshare',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='socialshare',
            name='share_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Share Date'),
        ),
        migrations.AlterField(
            model_name='socialshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='details',
            field=models.JSONField(verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
