# Generated by Django 5.0.2 on 2024-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean')], default='str', max_length=4)),
            ],
        ),
    ]
