# Generated by Django 5.0.2 on 2024-02-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingoption',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='duration',
            field=models.CharField(help_text='Estimated delivery time', max_length=100),
        ),
    ]
