# Generated by Django 5.0.2 on 2024-02-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productalert_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAlert',
        ),
    ]
